### ISSUE TITLE
(for auth project) Sign in with username

### ISSUE THREAD

**Issue by Time-dragon** [hamptonmoore/FluffyScratch#12]
so I can use Ocular with my IP ban

**Comment by hamptonmoore** [comment]
I will not be adding a username and password system. Ask @jeffalo

**Comment by jeffalo** [comment]
users banned from scratch are also banned from ocular.

**Comment by Time-dragon** [comment]
> users banned from scratch are also banned from ocular.

wrong

**Comment by hamptonmoore** [comment]
@Time-dragon, @jeffalo literally wrote and maintains Ocular.

**Comment by Time-dragon** [comment]
> I think he knows the policy.

"the policy" does not exist.
