### ISSUE TITLE
Embed the Scratch project

### ISSUE THREAD

**Issue by Samq64** [hamptonmoore/FluffyScratch#18]
As far as I know logged in users can set cloud data from embeds, so why not just embed the Scratch project on the FluffyScratch site so they don't need to open another tab to paste the code?

**Comment by jeffalo** [comment]
embeds can't do cloud data

**Comment by haylinmoore** [comment]
thanks jeffalo, I'll close

**Comment by haylinmoore** [comment]
bruh ninja'd the close
