### ISSUE TITLE
Automatically determine username

### ISSUE THREAD

**Issue by easrng** [hamptonmoore/FluffyScratch#5]
The cloud logs show the username anyway, no need to specify it in the URL. There should be a username-agnostic auth link, something like `https://fluffyscratch.hampton.pw/auth/getKeys/v2?redirect=c2NyYXRjaHN0YXR1cy1hcGkuZ2xpdGNoLm1lL2FjYWxi`

**Comment by hamptonmoore** [comment]
This has been implemented in version 2. Thank you :D
