### ISSUE TITLE
How to do verify?

### ISSUE THREAD

**Issue by robloxboy24** [hamptonmoore/FluffyScratch#6]
I was testing it and returned to my redirect link with the info, but I don't know what to do next, as I have no clue what `GET` is or how to get the info, or even check if it is true or false. I would really like some help.

**Comment by Zxnii** [comment]
please, why are you trying to do something when you dont even know what a `GET` request is, learn that before you try to use this api, there is literally no way you can use it without knowing this stuff, im not even going to try and help you are actually beyond brain dead

**Comment by hamptonmoore** [comment]
I'm sorry, but I believe @Zxnii, while coarsely worded, might be right. Using an API like this requires the knowledge to run a backend server to verify the validation, and a knowledge over how to properly use APIs. I suggets you look into REST APIs and technologies like Python and NodeJS for running backend servers

**Comment by Sussy-OS** [comment]
> please, why are you trying to do something when you dont even know what a `GET` request is, learn that before you try to use this api, there is literally no way you can use it without knowing this stuff, im not even going to try and help you are actually beyond brain dead

@Zxnii Please be nicer. Not everybody can learn things quickly. I beleive he was asking what `GET` was, and I'm not sure that your responce was the nicest.

**Comment by haylinmoore** [comment]
None of what I nor Zxnii knows comes from birth. It comes from research m

**Comment by Sussy-OS** [comment]
> None of what I nor Zxnii knows comes from birth. It comes from research m

Sorry, thats not what I meant. I just felt like Zxnii was a little harsh.
