### ISSUE TITLE
Better system

### ISSUE THREAD

**Issue by CodeGuy92** [hamptonmoore/FluffyScratch#8]
How about creating a banned.json file that stores all of the banned users, instead of just adding all of the banned users in 2 files ( **routes/auth/verify/v2.mjs** and **routes/user/[username]/notifications/handleNotificationRequest.mjs**)
And then dissallowing the user to continue if their username is on the list?

**Comment by hamptonmoore** [comment]
yeah that would make sense, but the current ban system was setup out of anger towards a single user and is not something I wish to continue, as I do not believe as an API owner I have the job of banning people

**Comment by CodeGuy92** [comment]
I kind of have to agree.

**Comment by Quantum-Codes** [comment]
Why everyone hates numbers man????
